# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-01 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='media',
            name='description',
            field=models.TextField(),
        ),
    ]
