# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-01 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160401_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
