# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-02 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_media_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='image',
            field=models.ImageField(blank=True, height_field=100, upload_to='blog/static/images', width_field=150),
        ),
        migrations.AlterField(
            model_name='media',
            name='created_date',
            field=models.DateTimeField(),
        ),
    ]
