# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-03 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160402_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='content',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.ImageField(blank=True, height_field=400, upload_to='blog/uploads/images', width_field=400),
        ),
    ]
