# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-04 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160403_2142'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Media',
            new_name='Project',
        ),
    ]
